---

all:
  children:
    build:
      hosts:
        localhost:
          ansible_connection: local

    demo:
      hosts:
        demo:
          ansible_connection: local

    live:
      hosts:
        live:
          ansible_connection: local

    server:
      children:
        demo:
        live:

