export enum ROUTES {
  HOME = 'HomeScreen',
  SCHEDULE = 'ScheduleScreen',
  NOTIFICATION = 'NotificationScreen',
  SUPPORT = 'SupportScreen',
  LOGIN = 'LoginScreen',
  REGISTER = 'RegisterScreen',
  NAVIGATOR= 'Navigator',
  QUESTION= 'QuestionScreen',
  RIGHTDRAWER='RightDrawer',
  SPECIFIC_QUESTION = 'SpecificQuestionScreen',
  TAB = "TabNavigation",
  COMMUNITYLIST= "CommunityListScreen",
  MORE_INFO="MoreInfoScreen",
  INIT_COMMUNITY="FirstJoinCommunityScreen",
  CHOOSE_CATEGORY="ChooseCategoryScreen",
  BOOKMARK= "BookMarkScreen",
  PROFILE= "UserProfileScreen",
  SETTING= "SettingScreen",
  CREATE_COMMUNITY= "CreateCommunityScreen",
  COMMUNITY = "CommunityScreen",
  USER_POST= "UserPostScreen",
  COMMUNITY_POST = "CommunityPostScreen",
  SEARCH = "SearchScreen",
  HEADER = "MainHeader",
  ANSWER_QUESTION = "AnswerQuestionScreen"
}
