---

- name: Run yarn to install node packages
  shell: yarn install
  args:
    chdir: '{{ workspace }}'

- name: Configure properties
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  loop:
    - {src: 'settings.js.j2', dest: '{{ workspace }}/config/settings.js'}

- name: Configure Android release key
  copy:
    src: release-key.keystore.vault
    dest: '{{ workspace }}/{{ android_build_path }}/app/release-key.keystore'

- name: Build Android apk release app
  shell: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 ./gradlew {{ item }}'
  args:
    chdir: '{{ workspace }}/{{ android_build_path }}'
  loop:
    - assembleRelease
    - bundleRelease

- name: Copy release apk file to packages server
  shell: 'scp {{ item }}'
  args:
    chdir: '{{ workspace }}'
  loop:
    - '{{ android_apk_file }} dmz:{{ android_release_path }}/{{ android_apk_release_file }}'
    - '{{ android_aab_file }} dmz:{{ android_release_path }}/{{ android_aab_release_file }}'
